# Generated by Django 3.1.3 on 2021-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mail_id', models.EmailField(max_length=254)),
                ('Qualification', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('Tel_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Candidate',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Mail_id', models.EmailField(max_length=254)),
                ('Company', models.CharField(max_length=100)),
                ('Tel_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Employer',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Description', models.CharField(max_length=100)),
                ('Tel_no', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Jobs',
            },
        ),
    ]
